version: '3.8'
services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-propertyapp}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-propertypassword}
      POSTGRES_DB: ${POSTGRES_DATABASE:-propertymanagement}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${POSTGRES_USER:-propertyapp} -d ${POSTGRES_DATABASE:-propertymanagement}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
