// src/config/subscription-plans.ts

export const SUBSCRIPTION_PLANS = {
  basic: {
    name: "Basic",
    description: "For individual landlords with a few properties",
    maxProperties: 5,
    maxUsers: 3,
    monthlyPriceId: "price_monthly_basic",
    yearlyPriceId: "price_yearly_basic",
    monthlyPrice: 29.99,
    yearlyPrice: 299.99,
    features: [
      "5 properties",
      "3 team members",
      "Property management",
      "Tenant management",
      "Basic reporting",
    ],
  },
  standard: {
    name: "Standard",
    description: "For growing property managers",
    maxProperties: 20,
    maxUsers: 10,
    monthlyPriceId: "price_monthly_standard",
    yearlyPriceId: "price_yearly_standard",
    monthlyPrice: 79.99,
    yearlyPrice: 799.99,
    features: [
      "20 properties",
      "10 team members",
      "All Basic features",
      "Advanced reporting",
      "Maintenance management",
      "Document storage",
    ],
  },
  premium: {
    name: "Premium",
    description: "For professional property management companies",
    maxProperties: 100,
    maxUsers: 50,
    monthlyPriceId: "price_monthly_premium",
    yearlyPriceId: "price_yearly_premium",
    monthlyPrice: 199.99,
    yearlyPrice: 1999.99,
    features: [
      "100 properties",
      "50 team members",
      "All Standard features",
      "API access",
      "Priority support",
      "Custom reports",
    ],
  },
  enterprise: {
    name: "Enterprise",
    description: "For large property management companies with custom needs",
    maxProperties: 500,
    maxUsers: 200,
    monthlyPriceId: "price_monthly_enterprise",
    yearlyPriceId: "price_yearly_enterprise",
    monthlyPrice: 499.99,
    yearlyPrice: 4999.99,
    features: [
      "500 properties",
      "200 team members",
      "All Premium features",
      "Dedicated support",
      "Custom integrations",
      "Advanced team management",
    ],
  },
};

export const TRIAL_DAYS = 30; // 1 month trial
