version: "3.8"
services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-propertyapp2}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-propertypassword2}
      POSTGRES_DB: ${POSTGRES_DATABASE:-propertymanagement2}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-propertyapp2} -d ${POSTGRES_DATABASE:-propertymanagement2}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
